INSERT INTO INVOICE(INVOICE_ID,AUTHOR,PAID,CREATE_DT,MODIFIED_DT)VALUES(1,'TEST',TRUE,{ts '2000-01-01'},{ts '2000-01-01'});
INSERT INTO INVOICE(INVOICE_ID,AUTHOR,PAID,CREATE_DT,MODIFIED_DT)VALUES(2,'TEST',FALSE,{ts '2000-01-01'},{ts '2000-01-01'});
INSERT INTO INVOICE(INVOICE_ID,AUTHOR,PAID,CREATE_DT,MODIFIED_DT)VALUES(3,'TEST',FALSE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());
INSERT INTO INVOICE(INVOICE_ID,AUTHOR,PAID,CREATE_DT,MODIFIED_DT)VALUES(4,'TEST',TRUE,CURRENT_TIMESTAMP(),CURRENT_TIMESTAMP());